### ISSUE TITLE
Use vm.runInThisContext instead of eval?

### ISSUE THREAD

**Issue by kevinsawicki** [groupon/cson-safe#17]
Just wondering why `eval` is used over `vm.runInThisContext` which is what CoffeeScript uses.

**Comment by jkrems** [comment]
Thanks! Yes, I felt bad committing that code. I think `eval` is already overkill. It should be possible to just parse the string according to JavaScript semantics. I'm not sure how much overhead `vm.runInThisContext` has, if it isn't completely crazy this might be worth it.

**Comment by kevinsawicki** [comment]
I think it is a little safer than eval according to http://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_filename since it can't touch local variables.

`eval` is going to be a problem in [Atom Shell](https://github.com/atom/atom-shell) apps that have a content security policy set on the page which prevents eval (among other things).

**Comment by jkrems** [comment]
Good point with the CSP, didn't consider that. I was fine with eval from a security perspective in this case because the coffee-script parser *should* guarantee those fields to be literals (e.g. no code involved). I would love for this code to run client-side but it looks like `vm` is actually supported, at least when using browserify. Will look into this.

**Comment by jkrems** [comment]
v1.0.4

**Comment by kevinsawicki** [comment]
Has 1.0.4 been published yet to npmjs.og?

**Comment by jkrems** [comment]
Oops :arrow_forward: #19

Published to public registry.

**Comment by kevinsawicki** [comment]
Awesome, thanks so much for this fix!
